(source gnu)
(source melpa)
(source marmalade)

;;; Programming tools
(depends-on "web-mode")
(depends-on "haml-mode")
(depends-on "sass-mode")
(depends-on "scss-mode")
(depends-on "yaml-mode")
(depends-on "flycheck")
(depends-on "flycheck-cask")

;;;; Coffee
(depends-on "coffee-mode")

;;;; Clojure
(depends-on "clojure-mode")
(depends-on "cider")
(depends-on "ac-cider")

;;;; Cypher
(depends-on "cypher-mode")

;;;; Docker
(depends-on "docker")
(depends-on "dockerfile-mode")

;;;; GLSL
(depends-on "glsl-mode")

;;;; Go
(depends-on "go-mode")

;;;; Haskell
(depends-on "haskell-mode")
(depends-on "ghci-completion")
(depends-on "shm")

;;;; Io
(depends-on "io-mode")
(depends-on "io-mode-inf")

;;;; Java
(depends-on "emacs-eclim")

;;;; JS
(depends-on "js2-mode")

;;;; Lisps
(depends-on "paredit")

;;;; Puppet
(depends-on "puppet-mode")

;;;; Purescript
(depends-on "purescript-mode")
(depends-on "psci")

;;;; Python
(depends-on "elpy")

;;;; R
(depends-on "ess")

;;;; Ruby
(depends-on "ruby-mode")
(depends-on "ruby-electric")
(depends-on "inf-ruby")
(depends-on "ruby-tools")
(depends-on "rvm")
(depends-on "robe")
(depends-on "ruby-hash-syntax")
(depends-on "rspec-mode")

;;;; Rust
(depends-on "rust-mode")
(depends-on "flycheck-rust")

;;;; Scala
(depends-on "scala-mode2")
(depends-on "ensime")
(depends-on "sbt-mode")

;;;; Scheme
(depends-on "geiser")

;;; General editing, programming and project tools
(depends-on "ace-jump-mode")
(depends-on "perspective")
(depends-on "auto-complete")
(depends-on "magit")
(depends-on "gist")
(depends-on "projectile")
(depends-on "iedit")
(depends-on "yasnippet")
(depends-on "highlight-indentation")
(depends-on "ack-and-a-half")
(depends-on "ag")
(depends-on "wgrep")
(depends-on "wgrep-ack")
(depends-on "wgrep-ag")
(depends-on "markdown-mode")
(depends-on "feature-mode")
(depends-on "multiple-cursors")
(depends-on "restclient")
(depends-on "dired-filter")
(depends-on "dired-subtree")
(depends-on "dired-ranger")
(depends-on "dired-narrow")
(depends-on "direx")

;; General emacs tools
(depends-on "evil")
(depends-on "undo-tree")
(depends-on "key-chord")
(depends-on "w3")
(depends-on "expand-region")
(depends-on "ecb")
(depends-on "tabulated-list")
(depends-on "jabber")
(depends-on "twittering-mode")
(depends-on "smart-mode-line")
(depends-on "rainbow-delimiters")
(depends-on "w3m")
(depends-on "window-numbering")
(depends-on "window-jump")
(depends-on "rotate")
(depends-on "git-gutter")
(depends-on "hydra")
(depends-on "browse-kill-ring")
(depends-on "guide-key")
(depends-on "discover-my-major")
(depends-on "visual-regexp")
(depends-on "repl-toggle")

;; General emacs tools: Helm
(depends-on "helm")
(depends-on "helm-projectile")
(depends-on "helm-ag")
(depends-on "helm-ls-git")
(depends-on "swiper-helm")

;; Libraries
(depends-on "f")    ; Directory and file api
(depends-on "dash") ; Modern list library

;; Extra
(depends-on "zone-nyan") ; Nyan cat zone
